id: PF44EB404
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: pt
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    ed1ca38caacf4c7ab147c71ad5d1db0f:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    95c482d48e4f44acbffeaac721a7d45e:
      title: The Benefits of Saving Lives
      parent: Advice
    42e68fd9f7294c57b1e3ee9b5e5a167d:
      title: Words of Advice
      parent: Advice
    827e429a1aa94d0d96fbbf299757c4e0:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    e3cc7c99adcb413aac93556e3300787a:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    1f89cb06b52f4290b84f560595dcf4e8:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    a8d9c8380cea4fd496d62a0b21ac11ee:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    9e85267ad6a5440ab5bee4b1ada89278:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    3fc476e2304c4454adccf146cfa1f0fc:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    d28225e0af4541e6b04ed5a00aef549d:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    5a7fc5cce4e7436dbd6243c4024ba85f:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    7e9ccb6bdd0a4f1f9f562757dc5ce744:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    86c538f4df63439bb80c1c71ba104699:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    220f80777d854033960aee1e6480ebf1:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.131656'
last_modified_at: '2022-02-28T22:42:38.131658'
